[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#
configs = {path = "../configs"}
db = {path = "../db"}
app-service = {path = "../service"}
middleware-fn = {path="../middleware-fn"}
# 
axum = {workspace = true, default-features =false, features = ["headers","multipart","original-uri"]}
tower-http = {workspace = true,  features = ["cors","fs"]}
# 
futures = {workspace = true}
# 
tokio-stream = {workspace = true}
# 
serde_json = {workspace = true}
# 
headers = {workspace = true}
# 
tokio = {workspace = true, default-features =false}
#
anyhow = {workspace = true}
# 
reqwest = {workspace = true,  features = ["json"]}


#  openApi
utoipa = { workspace = true, features = ["axum_extras"] }