//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::sys_config::Entity as SysConfig;
pub use super::sys_dept::Entity as SysDept;
pub use super::sys_dict_data::Entity as SysDictData;
pub use super::sys_dict_type::Entity as SysDictType;
pub use super::sys_job::Entity as SysJob;
pub use super::sys_job_log::Entity as SysJobLog;
pub use super::sys_login_info_record::Entity as SysLoginInfoRecord;
pub use super::sys_menu::Entity as SysMenu;
pub use super::sys_notice::Entity as SysNotice;
pub use super::sys_operate_log::Entity as SysOperateLog;
pub use super::sys_post::Entity as SysPost;
pub use super::sys_role::Entity as SysRole;
pub use super::sys_role_dept::Entity as SysRoleDept;
pub use super::sys_role_menu::Entity as SysRoleMenu;
pub use super::sys_user::Entity as SysUser;
pub use super::sys_user_dept::Entity as SysUserDept;
pub use super::sys_user_online::Entity as SysUserOnline;
pub use super::sys_user_post::Entity as SysUserPost;
pub use super::sys_user_role::Entity as SysUserRole;
