//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_operate_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub title: Option<String>,
    pub business_type: Option<i32>,
    pub method: Option<String>,
    pub request_method: Option<String>,
    pub operator_type: Option<i32>,
    pub operator_name: Option<String>,
    pub dept_name: Option<String>,
    pub operate_url: Option<String>,
    pub operate_ip: Option<String>,
    pub operate_location: Option<String>,
    pub operate_param: Option<String>,
    pub json_result: Option<Json>,
    pub status: Option<i32>,
    pub error_msg: Option<String>,
    pub operate_time: Option<DateTime>,
    pub cost_time: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
